pipeline {
    agent any

    stages {

        stage('Clone Repository') {
    steps {
        git branch: 'main', url: 'https://github.com/pranavkaranam55/DevopsNetflixProject.git'
    }
}

        stage('Build Docker Image') {
            steps {
                sh 'docker build -t netflix-app ./app'
            }
        }

        stage('Run Container') {
            steps {
                sh 'docker stop netflix-container || true'
                sh 'docker rm netflix-container || true'
                sh 'docker run -d -p 3001:3000 --name netflix-container netflix-app'
            }
        }

    }
}