pipeline {
    agent any

    stages {

        stage('Checkout Code') {
            steps {
                git branch: 'main', url: 'https://github.com/pranavkaranam55/DevopsNetflixProject.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                sh 'docker build -t netflix-app ./app'
            }
        }

        stage('Remove Old Container') {
            steps {
                sh 'docker rm -f netflix-container || true'
            }
        }

        stage('Run Netflix Container') {
            steps {
                sh 'docker run -d -p 3001:3000 --name netflix-container netflix-app'
            }
        }

        stage('Start Monitoring Containers') {
    steps {
        sh '''
        docker rm -f prometheus || true
        docker rm -f grafana || true
        docker rm -f node-exporter || true

        docker run -d --name=node-exporter -p 9100:9100 prom/node-exporter

        docker run -d --name=prometheus -p 9090:9090 \
        -v /var/run/docker.sock:/var/run/docker.sock \
        prom/prometheus

        docker run -d --name=grafana -p 3002:3000 grafana/grafana
        '''
    }
    }
    }

    post {
        success {
            echo '✅ CI/CD Pipeline with Monitoring Completed Successfully'
        }
        failure {
            echo '❌ Pipeline Failed'
        }
    }
}